site_name: Dotsec
site_author: JP Wesselink
copyright: (c) 2023 by JP Wesselink
repo_url: https://github.com/jpwesselink/dotsec
plugins:
  - search
nav:
  - Dotwhat?: README.md
  - Commands:
      - init: commands/init.md
      - run: commands/run.md
      - encrypt: commands/encrypt.md
      - decrypt: commands/decrypt.md
      - push: commands/push.md
  - Plugins:
      - AWS:
          - plugins/aws/README.md
          - Commands:
              - init: plugins/aws/commands/init.md
      - PKE: plugins/pke.md
  - Guides:
      - Multiple environments: guides/multiple-environments.md
  - Reference:
      - dotsec.config.ts: reference/config.md
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: pink
      scheme: default
      accent: purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
