name: Publish
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths-ignore:
      - "**.md"
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install NPM dependencies
        id: install-npm
        shell: bash
        run: yarn --frozen-lockfile

      - name: Build
        run: |
          yarn turbo build

      - name: setup github name/email
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: "NPM Identity"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - name: Publish pre-release
        if: ${{ github.event_name == 'pull_request' && github.base_ref == 'main' }}
        run: |
          yarn lerna publish --no-verify-access --canary --preid beta.$(git rev-parse --short HEAD)
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          yarn lerna publish --force-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish docs
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          pip install mkdocs-material \
          mkdocs gh-deploy --force
