name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - feat/modules
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
