name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Install NPM dependencies
        id: install-npm
        shell: bash
        run: yarn --frozen-lockfile

      - name: Build
        run: |
          yarn turbo build
          
      - name: Versioning
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          yarn lerna version --conventional-commits --yes
        
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
